# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b3bdba372284814416b7b26ff9bce95"
name = "gpt-feed"
handle = "gpt-feed-1"
application_url = "https://gst-feed.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_products"

[auth]
redirect_urls = [
  "https://gst-feed.onrender.com/auth/callback",
  "https://gst-feed.onrender.com/auth/shopify/callback",
  "https://gst-feed.onrender.com/api/auth/callback"
]

[pos]
embedded = false
